### ISSUE TITLE
Chance of supporting Coq 8.7.1?

### ISSUE THREAD

**Issue by jimyu94** [mit-plv/kami#1]
Hi! I am currently learning Coq, and looking at Coq projects! Kami seems interesting to me, but I cannot compile it under Coq 8.7.1. Do you have plans to commit a version compatible with it? Thanks!

**Comment by joonwonc** [comment]
Hi! I'm sorry for the very late response, but we've just added a branch that is compatible with Coq 8.8.0! Note that this version unfortunately does not work with Coq 8.7.* due to a known bug (about universe polymorphism). This bug was fixed in Coq 8.8.0, so I recommend you to try the up-to-date version. Hope this is helpful to you!
